/* js_84926301910afc4b800b75e5dd90cf61.jquery.ui.autocomplete.html.js */
(function($){var proto=$.ui.autocomplete.prototype,initSource=proto._initSource;function filter(array,term){var matcher=new RegExp($.ui.autocomplete.escapeRegex(term),"i");return $.grep(array,function(value){return matcher.test($("<div>").html(value.label||value.value||value).text());});}
$.extend(proto,{_initSource:function(){if(this.options.html&&$.isArray(this.options.source)){this.source=function(request,response){response(filter(this.options.source,request.term));};}else{initSource.call(this);}},_renderItem:function(ul,item){return $("<li></li>").data("item.autocomplete",item).append($("<a></a>")[this.options.html?"html":"text"](item.label)).appendTo(ul);}});})(jQuery);;;

/* js_50468f55aa04e8698a5afbee8cc17719.jquery.noconflict.js */
jQuery.noConflict();;;

/* js_dc444e1a59af69ba749fb78b7a4c7f29.vmsite.js */
var Virtuemart=window.Virtuemart||{};(function($){var methods={_cache:{},list:function(options){if(typeof Virtuemart.vmSiteurl==='undefined')Virtuemart.vmSiteurl='';return this.each(function(){this.self=$(this);this.opt=this.opt||{};this.opt=$.extend(true,{},$.fn.vm2front.defaults,this.opt,methods._processOpt(options));this.form=$(this).closest('form');this.state_fields=$(this.form).find(this.opt.state_field_selector);methods._update.call(this,false);$(this).on('change',function(){methods._update.call(this,this.opt.show_list_loader);});});},setOpt:function(options){return this.each(function(){this.opt=$.extend(true,{},$.fn.vm2front.defaults,this.opt,methods._processOpt(options));});},_processOpt:function(options){if(options.hasOwnProperty('dest')){options['state_field_selector']=options.dest;delete options.dest;}
if(options.hasOwnProperty('ids')){options['selected_state_ids']=options.ids;delete options.ids;}
if(options.hasOwnProperty('prefiks')){options['field_prefix']=options.prefiks;delete options.prefiks;}
return options;},_update:function(showLoader){var that=this,selected_country_ids=$(this).val()||[];if(!$.isArray(selected_country_ids)){selected_country_ids=$.makeArray(selected_country_ids);}
if(selected_country_ids.length){selected_country_ids=selected_country_ids.join(',');if(methods._cache.hasOwnProperty(selected_country_ids)){methods._addToList.call(that,methods._cache[selected_country_ids]);}else{$.ajax({dataType:'JSON',url:Virtuemart.vmSiteurl+'index.php?option=com_virtuemart&view=state&format=json&virtuemart_country_id='+selected_country_ids,beforeSend:function(){if(showLoader){methods.startVmLoading();}},success:function(data){if(data){methods._cache[selected_country_ids]=data;methods._addToList.call(that,methods._cache[selected_country_ids]);}
if(showLoader){methods.stopVmLoading();}},error:function(e,t,n){console.log(e);console.log(t);console.log(n);if(showLoader){methods.stopVmLoading();}}})}}},_addToList:function(data){var that=this,dataType=$.type(data),i=0;selected_state_ids=[];if(that.opt.selected_state_ids&&that.opt.selected_state_ids.length){if(that.opt.selected_state_ids){if($.type(that.opt.selected_state_ids)==='string'){selected_state_ids=that.opt.selected_state_ids.split(',');}
if($.type(that.opt.selected_state_ids)==='number'){selected_state_ids.push(that.opt.selected_state_ids);}}}
$(that.state_fields).each(function(){var state_field=this,id=$(this).attr('id'),form=$(that.form),label=id&&form.length?form.find('label[for="'+id+'"]'):null,required=$(state_field).data('required'),hasData=false;$(state_field).data('label',label);if((required!==true&&required!==false)||($(state_field).attr('required')||$(state_field).hasClass('required'))){if($(state_field).attr('required')||$(state_field).hasClass('required')){$(state_field).data('required',true).removeAttr('required').removeAttr('aria-required').removeClass('required');if(label&&label.length&&that.opt.asterisk_class){label.find('.'+that.opt.asterisk_class).hide();}}else{$(state_field).data('required',false);}}
$('optgroup',state_field).each(function(){if($(this).data('ajaxloaded'))$(this).remove();});if(dataType==='object'||dataType==='array'){hasData=false;$.each(data,function(country_id,states){var country_name=$(that).find('option[value="'+country_id+'"]').text(),prefix=that.opt.field_prefix?that.opt.field_prefix+'-':that.opt.field_prefix,optgroup_id=prefix+'group-'+i+'-'+country_id,optgroup,option;if(!$('#'+optgroup_id,this).length){optgroup=$('<optgroup />',{id:optgroup_id,label:country_name}).data('ajaxloaded',true);$.each(states,function(index,state){option=$('<option />',{value:state.virtuemart_state_id}).text(state.state_name);if($.inArray(state.virtuemart_state_id,selected_state_ids)>=0){option.attr('selected',true);}
optgroup.append(option);hasData=true;});}
if(optgroup&&hasData){$(state_field).append(optgroup);}});}
if(hasData&&$(state_field).data('required')){$(state_field).attr('required',true).attr('aria-required',true);label=$(state_field).data('label');if(label&&$(label).length&&that.opt.asterisk_class){$(label).find('.'+that.opt.asterisk_class).show();}}
if($(state_field).hasClass('invalid')||$(state_field).attr('aria-invalid')=='true'){$(state_field).trigger('blur');}
if(that.opt.field_update_trigger&&$.type(that.opt.field_update_trigger)==='string'){$(state_field).trigger(that.opt.field_update_trigger);}
i++;});},startVmLoading:function(message){var object={data:{msg:(!message?'':message)}};Virtuemart.startVmLoading(object);},stopVmLoading:function(){Virtuemart.stopVmLoading();}};$.fn.vm2front=function(method){if(methods[method]){return methods[method].apply(this,Array.prototype.slice.call(arguments,1));}else if(typeof method==='object'||!method){return methods.init.apply(this,arguments);}else{$.error('Method '+method+' does not exist in Vm2front plugin.');}};$.fn.vm2front.defaults={state_field_selector:'#virtuemart_state_id_field',selected_state_ids:'',field_prefix:'',field_update_trigger:'liszt:updated',show_list_loader:true,asterisk_class:'asterisk'};Virtuemart.startVmLoading=function(a){var msg='';if(typeof a.data.msg!=='undefined'){msg=a.data.msg;}
$('body').addClass('vmLoading');if(!$('div.vmLoadingDiv').length){$('body').append('<div class="vmLoadingDiv"><div class="vmLoadingDivMsg">'+msg+'</div></div>');}};Virtuemart.stopVmLoading=function(){if($('body').hasClass('vmLoading')){$('body').removeClass('vmLoading');$('div.vmLoadingDiv').remove();}};Virtuemart.sendCurrForm=function(event){event.preventDefault();if(event.currentTarget.length>0){$(event.currentTarget[0].form.submit());}else{var f=jQuery(event.currentTarget).closest('form');f.submit();}}})(jQuery);;

/* js_4368bd92d005ea6d1df2f0f34799b9a5.core.js */
function switchFontSize(ckname,val){var bd=document.getElementsByTagName('body');if(!bd||!bd.length)return;bd=bd[0];switch(val){case'inc':if(CurrentFontSize+1<7){CurrentFontSize++;}
break;case'dec':if(CurrentFontSize-1>0){CurrentFontSize--;}
break;case'reset':default:CurrentFontSize=DefaultFontSize;}
var newclass='fs'+CurrentFontSize;bd.className=bd.className.replace(new RegExp('fs.?','g'),'');bd.className=trim(bd.className);bd.className+=(bd.className?' ':'')+newclass;createCookie(ckname,CurrentFontSize,365);}
function switchTool(ckname,val){createCookie(ckname,val,365);window.location.reload();}
function cpanel_reset(){var matches=document.cookie.match(new RegExp('(?:^|;)\\s*'+tmpl_name.escapeRegExp()+'_([^=]*)=([^;]*)','g'));if(!matches)return;for(var i=0;i<matches.length;i++){var ck=matches[i].match(new RegExp('(?:^|;)\\s*'+tmpl_name.escapeRegExp()+'_([^=]*)=([^;]*)'));if(ck){createCookie(tmpl_name+'_'+ck[1],'',-1);}}
if(window.location.href.indexOf('?')>-1){window.location.href=window.location.href.substr(0,window.location.href.indexOf('?'));}else{window.location.reload(true);}}
function cpanel_apply(){var elems=document.getElementById('ja-cpanel-main').getElementsByTagName('*');var usersetting={};for(var i=0;i<elems.length;i++){var el=elems[i];if(el.name&&(match=el.name.match(/^user_(.*)$/))){var name=match[1];var value='';if(el.tagName.toLowerCase()=='input'&&(el.type.toLowerCase()=='radio'||el.type.toLowerCase()=='checkbox')){if(el.checked)value=el.value;}else{value=el.value;}
if(usersetting[name]){if(value)usersetting[name]=value+','+usersetting[name];}else{usersetting[name]=value;}}}
for(var k in usersetting){name=tmpl_name+'_'+k;value=usersetting[k].trim();if(value.length>0){createCookie(name,value,365);}}
if(window.location.href.indexOf('?')>-1){window.location.href=window.location.href.substr(0,window.location.href.indexOf('?'));}else{window.location.reload(true);}}
function createCookie(name,value,days){if(days){var date=new Date();date.setTime(date.getTime()+(days*24*60*60*1000));var expires="; expires="+date.toGMTString();}else{expires="";}
document.cookie=name+"="+value+expires+"; path=/";}
function trim(str,chars){return ltrim(rtrim(str,chars),chars);}
function ltrim(str,chars){chars=chars||"\\s";return str.replace(new RegExp("^["+chars+"]+","g"),"");}
function rtrim(str,chars){chars=chars||"\\s";return str.replace(new RegExp("["+chars+"]+$","g"),"");}
function getScreenWidth(){var x=0;if(self.innerHeight){x=self.innerWidth;}else if(document.documentElement&&document.documentElement.clientHeight){x=document.documentElement.clientWidth;}else if(document.body){x=document.body.clientWidth;}
return x;}
function equalHeight(els){els=$$_(els);if(!els||els.length<2)return;var maxh=0;var els_=[];els.each(function(el,i){if(!el)return;els_[i]=el;var ch=els_[i].getCoordinates().height;maxh=(maxh<ch)?ch:maxh;},this);els_.each(function(el,i){if(!el)return;if(el.getStyle('padding-top')!=null&&el.getStyle('padding-bottom')!=null){if(maxh-el.getStyle('padding-top').toInt()-el.getStyle('padding-bottom').toInt()>0){el.setStyle('min-height',maxh-el.getStyle('padding-top').toInt()-el.getStyle('padding-bottom').toInt());}}else{if(maxh>0)el.setStyle('min-height',maxh);}},this);}
function getDeepestWrapper(el){while(el.getChildren().length==1){el=el.getChildren()[0];}
return el;}
function fixHeight(els,group1,group2){els=$$_(els);group1=$$_(group1);group2=$$_(group2);if(!els||!group1)return;var height=0;group1.each(function(el){if(!el)return;height+=el.getCoordinates().height;});if(group2){group2.each(function(el){if(!el)return;height-=el.getCoordinates().height;});}
els.each(function(el,i){if(!el)return;if(el.getStyle('padding-top')!=null&&el.getStyle('padding-bottom')!=null){if(height-el.getStyle('padding-top').toInt()-el.getStyle('padding-bottom').toInt()>0){el.setStyle('min-height',height-el.getStyle('padding-top').toInt()-el.getStyle('padding-bottom').toInt());}}else{if(height>0){el.setStyle('min-height',height);}}});}
function addFirstLastItem(el){el=$(el);if(!el||!el.getChildren()||!el.getChildren().length)return;el.getChildren()[0].addClass('first-item');el.getChildren()[el.getChildren().length-1].addClass('last-item');}
function $$_(els){if(typeOf(els)=='string')return $$(els);var els_=[];els.each(function(el){el=$(el);if(el)els_.push(el);});return els_;}
$(document).addEvent('domready',function(){$$('[data-dismiss="alert"]').each(function(el){el.addEvent('click',function(){el.getParent().destroy();if($('system-message').getChildren().length==0){Joomla.removeMessages();}});});});;;

