/* VirtueMart Product import */
INSERT IGNORE INTO `#__csvi_availablefields` (`csvi_name`, `component_name`, `component_table`, `component`, `action`)
VALUES
  ('skip', 'skip', 'product', 'com_virtuemart', 'import'),
  ('combine', 'combine', 'product', 'com_virtuemart', 'import'),
  ('product_discount', 'product_discount', 'product', 'com_virtuemart', 'import'),
  ('product_discount_date_start', 'product_discount_date_start', 'product', 'com_virtuemart', 'import'),
  ('product_discount_date_end', 'product_discount_date_end', 'product', 'com_virtuemart', 'import'),
  ('calc_kind', 'calc_kind', 'product', 'com_virtuemart', 'import'),
  ('product_price', 'product_price', 'product', 'com_virtuemart', 'import'),
  ('shopper_group_name', 'shopper_group_name', 'product', 'com_virtuemart', 'import'),
  ('shopper_group_name_new', 'shopper_group_name_new', 'product', 'com_virtuemart', 'import'),
  ('shopper_group_name_price', 'shopper_group_name_price', 'product', 'com_virtuemart', 'import'),
  ('related_products', 'related_products', 'product', 'com_virtuemart', 'import'),
  ('related_categories', 'related_categories', 'product', 'com_virtuemart', 'import'),
  ('category_id', 'category_id', 'product', 'com_virtuemart', 'import'),
  ('category_path', 'category_path', 'product', 'com_virtuemart', 'import'),
  ('manufacturer_name', 'manufacturer_name', 'product', 'com_virtuemart', 'import'),
  ('manufacturer_id', 'manufacturer_id', 'product', 'com_virtuemart', 'import'),
  ('price_with_tax', 'price_with_tax', 'product', 'com_virtuemart', 'import'),
  ('product_tax_id', 'product_tax_id', 'product', 'com_virtuemart', 'import'),
  ('product_override_price', 'product_override_price', 'product', 'com_virtuemart', 'import'),
  ('override', 'override', 'product', 'com_virtuemart', 'import'),
  ('product_box', 'product_box', 'product', 'com_virtuemart', 'import'),
  ('product_delete', 'product_delete', 'product', 'com_virtuemart', 'import'),
  ('product_name', 'product_name', 'product', 'com_virtuemart', 'import'),
  ('product_s_desc', 'product_s_desc', 'product', 'com_virtuemart', 'import'),
  ('product_desc', 'product_desc', 'product', 'com_virtuemart', 'import'),
  ('metadesc', 'metadesc', 'product', 'com_virtuemart', 'import'),
  ('metakey', 'metakey', 'product', 'com_virtuemart', 'import'),
  ('customtitle', 'customtitle', 'product', 'com_virtuemart', 'import'),
  ('slug', 'slug', 'product', 'com_virtuemart', 'import'),
  ('file_url', 'file_url', 'product', 'com_virtuemart', 'import'),
  ('file_url_thumb', 'file_url_thumb', 'product', 'com_virtuemart', 'import'),
  ('file_title', 'file_title', 'product', 'com_virtuemart', 'import'),
  ('file_description', 'file_description', 'product', 'com_virtuemart', 'import'),
  ('file_meta', 'file_meta', 'product', 'com_virtuemart', 'import'),
  ('file_ordering', 'file_ordering', 'product', 'com_virtuemart', 'import'),
  ('product_tax', 'product_tax', 'product', 'com_virtuemart', 'import'),
  ('product_parent_sku', 'product_parent_sku', 'product', 'com_virtuemart', 'import'),
  ('product_delete', 'product_delete', 'product', 'com_virtuemart', 'import'),
  ('product_currency', 'product_currency', 'product', 'com_virtuemart', 'import'),
  ('custom_title', 'custom_title', 'product', 'com_virtuemart', 'import'),
  ('custom_value', 'custom_value', 'product', 'com_virtuemart', 'import'),
  ('custom_price', 'custom_price', 'product', 'com_virtuemart', 'import'),
  ('custom_param', 'custom_param', 'product', 'com_virtuemart', 'import'),
  ('custom_ordering', 'custom_ordering', 'product', 'com_virtuemart', 'import'),
  ('custom_multiple', 'custom_multiple', 'product', 'com_virtuemart', 'import'),
  ('custom_delete', 'custom_delete', 'product', 'com_virtuemart', 'import'),
  ('custom_disabler', 'custom_disabler', 'product', 'com_virtuemart', 'import'),
  ('custom_override', 'custom_override', 'product', 'com_virtuemart', 'import'),
  ('features', 'features', 'product', 'com_virtuemart', 'import'),
  ('min_order_level', 'min_order_level', 'product', 'com_virtuemart', 'import'),
  ('max_order_level', 'max_order_level', 'product', 'com_virtuemart', 'import'),
  ('step_order_level', 'step_order_level', 'product', 'com_virtuemart', 'import'),
  ('product_tax_id', 'product_tax_id', 'product', 'com_virtuemart', 'import'),
  ('product_discount_id', 'product_discount_id', 'product', 'com_virtuemart', 'import'),
  ('product_ordering', 'product_ordering', 'product', 'com_virtuemart', 'import'),
  ('multi_variant_title', 'multi_variant_title', 'product', 'com_virtuemart', 'import'),
  ('multi_variant_fields', 'multi_variant_fields', 'product', 'com_virtuemart', 'import'),
  ('vendor_name', 'vendor_name', 'product', 'com_virtuemart', 'import'),
  ('media_published', 'media_published', 'product', 'com_virtuemart', 'import'),
  ('product_as_derived', 'product_as_derived', 'product', 'com_virtuemart', 'import'),

  /* VirtueMart Category import */
  ('skip', 'skip', 'category', 'com_virtuemart', 'import'),
  ('combine', 'combine', 'category', 'com_virtuemart', 'import'),
  ('category_path', 'category_path', 'category', 'com_virtuemart', 'import'),
  ('category_path_trans', 'category_path_trans', 'category', 'com_virtuemart', 'import'),
  ('category_name', 'category_name', 'category', 'com_virtuemart', 'import'),
  ('category_description', 'category_description', 'category', 'com_virtuemart', 'import'),
  ('metadesc', 'metadesc', 'category', 'com_virtuemart', 'import'),
  ('metakey', 'metakey', 'category', 'com_virtuemart', 'import'),
  ('customtitle', 'customtitle', 'category', 'com_virtuemart', 'import'),
  ('slug', 'slug', 'category', 'com_virtuemart', 'import'),
  ('category_delete', 'category_delete', 'category', 'com_virtuemart', 'import'),
  ('file_url', 'file_url', 'category', 'com_virtuemart', 'import'),
  ('file_url_thumb', 'file_url_thumb', 'category', 'com_virtuemart', 'import'),
  ('file_title', 'file_title', 'category', 'com_virtuemart', 'import'),
  ('file_description', 'file_description', 'category', 'com_virtuemart', 'import'),
  ('file_meta', 'file_meta', 'category', 'com_virtuemart', 'import'),
  ('media_published', 'media_published', 'category', 'com_virtuemart', 'import'),

  /* VirtueMart Manufacturer Categories import */
  ('skip', 'skip', 'manufacturercategory', 'com_virtuemart', 'import'),
  ('combine', 'combine', 'manufacturercategory', 'com_virtuemart', 'import'),
  ('mf_category_name', 'mf_category_name', 'manufacturercategory', 'com_virtuemart', 'import'),
  ('mf_category_name_trans', 'mf_category_name_trans', 'manufacturercategory', 'com_virtuemart', 'import'),
  ('mf_category_desc', 'mf_category_desc', 'manufacturercategory', 'com_virtuemart', 'import'),
  ('slug', 'slug', 'manufacturercategory', 'com_virtuemart', 'import'),
  ('mf_category_delete', 'mf_category_delete', 'manufacturercategory', 'com_virtuemart', 'import'),

  /* VirtueMart Manufacturer import */
  ('skip', 'skip', 'manufacturer', 'com_virtuemart', 'import'),
  ('combine', 'combine', 'manufacturer', 'com_virtuemart', 'import'),
  ('mf_name', 'mf_name', 'manufacturer', 'com_virtuemart', 'import'),
  ('mf_name_trans', 'mf_name_trans', 'manufacturer', 'com_virtuemart', 'import'),
  ('mf_email', 'mf_email', 'manufacturer', 'com_virtuemart', 'import'),
  ('mf_desc', 'mf_desc', 'manufacturer', 'com_virtuemart', 'import'),
  ('mf_url', 'mf_url', 'manufacturer', 'com_virtuemart', 'import'),
  ('slug', 'slug', 'manufacturer', 'com_virtuemart', 'import'),
  ('mf_category_name', 'mf_category_name', 'manufacturer', 'com_virtuemart', 'import'),
  ('manufacturer_delete', 'manufacturer_delete', 'manufacturer', 'com_virtuemart', 'import'),
  ('file_url', 'file_url', 'manufacturer', 'com_virtuemart', 'import'),
  ('file_url_thumb', 'file_url_thumb', 'manufacturer', 'com_virtuemart', 'import'),
  ('file_title', 'file_title', 'manufacturer', 'com_virtuemart', 'import'),
  ('file_description', 'file_description', 'manufacturer', 'com_virtuemart', 'import'),
  ('file_meta', 'file_meta', 'manufacturer', 'com_virtuemart', 'import'),
  ('file_ordering', 'file_ordering', 'manufacturer', 'com_virtuemart', 'import'),
  ('media_published', 'media_published', 'manufacturer', 'com_virtuemart', 'import'),

  /* VirtueMart rating import */
  ('skip', 'skip', 'rating', 'com_virtuemart', 'import'),
  ('combine', 'combine', 'rating', 'com_virtuemart', 'import'),
  ('product_sku', 'product_sku', 'rating', 'com_virtuemart', 'import'),
  ('vote', 'vote', 'rating', 'com_virtuemart', 'import'),
  ('username', 'username', 'rating', 'com_virtuemart', 'import'),

  /* VirtueMart medias import */
  ('skip', 'skip', 'media', 'com_virtuemart', 'import'),
  ('combine', 'combine', 'media', 'com_virtuemart', 'import'),
  ('product_sku', 'product_sku', 'media', 'com_virtuemart', 'import'),
  ('media_delete', 'media_delete', 'media', 'com_virtuemart', 'import'),

  /* VirtueMart order import */
  ('skip', 'skip', 'order', 'com_virtuemart', 'import'),
  ('combine', 'combine', 'order', 'com_virtuemart', 'import'),
  ('user_currency', 'user_currency', 'order', 'com_virtuemart', 'import'), /* In the format EUR */
  ('payment_element', 'payment_element', 'order', 'com_virtuemart', 'import'),
  ('state_name', 'state_name', 'order', 'com_virtuemart', 'import'),
  ('state_2_code', 'state_2_code', 'order', 'com_virtuemart', 'import'),
  ('state_3_code', 'state_3_code', 'order', 'com_virtuemart', 'import'),
  ('virtuemart_state_id', 'virtuemart_state_id', 'order', 'com_virtuemart', 'import'),
  ('country_name', 'country_name', 'order', 'com_virtuemart', 'import'),
  ('country_2_code', 'country_2_code', 'order', 'com_virtuemart', 'import'),
  ('country_3_code', 'country_3_code', 'order', 'com_virtuemart', 'import'),
  ('virtuemart_country_id', 'virtuemart_country_id', 'order', 'com_virtuemart', 'import'),
  ('shipment_element', 'shipment_element', 'order', 'com_virtuemart', 'import'),
  ('order_status_name', 'order_status_name', 'order', 'com_virtuemart', 'import'),
  ('customer_notified', 'customer_notified', 'order', 'com_virtuemart', 'import'),
  ('comments', 'comments', 'order', 'com_virtuemart', 'import'),
  ('order_status_code', 'order_status_code', 'order', 'com_virtuemart', 'import'),

  /* VirtueMart order item import */
  ('skip', 'skip', 'orderitem', 'com_virtuemart', 'import'),
  ('combine', 'combine', 'orderitem', 'com_virtuemart', 'import'),
  ('product_sku', 'product_sku', 'orderitem', 'com_virtuemart', 'import'),
  ('order_status_name', 'order_status_name', 'orderitem', 'com_virtuemart', 'import'),

  /* VirtueMart shopperfield import */
  ('skip', 'skip', 'shopperfield', 'com_virtuemart', 'import'),
  ('combine', 'combine', 'shopperfield', 'com_virtuemart', 'import'),
  ('shopperfield_delete', 'shopperfield_delete', 'shopperfield', 'com_virtuemart', 'import'),

  /* VirtueMart Userinfo import */
  ('skip', 'skip', 'userinfo', 'com_virtuemart', 'import'),
  ('combine', 'combine', 'userinfo', 'com_virtuemart', 'import'),
  ('vendor_name', 'vendor_name', 'userinfo', 'com_virtuemart', 'import'),
  ('shopper_group_name', 'shopper_group_name', 'userinfo', 'com_virtuemart', 'import'),
  ('address_type', 'address_type', 'userinfo', 'com_virtuemart', 'import'),
  ('address_type_name', 'address_type_name', 'userinfo', 'com_virtuemart', 'import'),
  ('usergroup_name', 'usergroup_name', 'userinfo', 'com_virtuemart', 'import'),
  ('state', 'state', 'userinfo', 'com_virtuemart', 'import'),
  ('country', 'country', 'userinfo', 'com_virtuemart', 'import'),
  ('password_crypt', 'password_crypt', 'userinfo', 'com_virtuemart', 'import'),

  /* VirtueMart waiting users import */
  ('skip', 'skip', 'waitinglist', 'com_virtuemart', 'import'),
  ('combine', 'combine', 'waitinglist', 'com_virtuemart', 'import'),
  ('product_sku', 'product_sku', 'waitinglist', 'com_virtuemart', 'import'),
  ('username', 'username', 'waitinglist', 'com_virtuemart', 'import'),

  /* VirtueMart custom field import */
  ('skip', 'skip', 'customfield', 'com_virtuemart', 'import'),
  ('combine', 'combine', 'customfield', 'com_virtuemart', 'import'),
  ('plugin_name', 'plugin_name', 'customfield', 'com_virtuemart', 'import'),
  ('vendor_name', 'vendor_name', 'customfield', 'com_virtuemart', 'import'),

  /* VirtueMart calculation rule import */
  ('skip', 'skip', 'calc', 'com_virtuemart', 'import'),
  ('combine', 'combine', 'calc', 'com_virtuemart', 'import'),
  ('currency_code_3', 'currency_code_3', 'calc', 'com_virtuemart', 'import'),
  ('category_path', 'category_path', 'calc', 'com_virtuemart', 'import'),
  ('shopper_group_name', 'shopper_group_name', 'calc', 'com_virtuemart', 'import'),
  ('manufacturer_name', 'manufacturer_name', 'calc', 'com_virtuemart', 'import'),
  ('country_name', 'country_name', 'calc', 'com_virtuemart', 'import'),
  ('country_2_code', 'country_2_code', 'calc', 'com_virtuemart', 'import'),
  ('country_3_code', 'country_3_code', 'calc', 'com_virtuemart', 'import'),
  ('state_name', 'state_name', 'calc', 'com_virtuemart', 'import'),
  ('state_2_code', 'state_2_code', 'calc', 'com_virtuemart', 'import'),
  ('state_3_code', 'state_3_code', 'calc', 'com_virtuemart', 'import'),

  /* VirtueMart category export */
  ('custom', 'custom', 'category', 'com_virtuemart', 'export'),
  ('category_path', 'category_path', 'category', 'com_virtuemart', 'export'),
  ('category_path_trans', 'category_path_trans', 'category', 'com_virtuemart', 'export'),
  ('category_name', 'category_name', 'category', 'com_virtuemart', 'export'),
  ('category_description', 'category_description', 'category', 'com_virtuemart', 'export'),
  ('metadesc', 'metadesc', 'category', 'com_virtuemart', 'export'),
  ('metakey', 'metakey', 'category', 'com_virtuemart', 'export'),
  ('customtitle', 'customtitle', 'category', 'com_virtuemart', 'export'),
  ('slug', 'slug', 'category', 'com_virtuemart', 'export'),
  ('file_url', 'file_url', 'category', 'com_virtuemart', 'export'),
  ('file_url_thumb', 'file_url_thumb', 'category', 'com_virtuemart', 'export'),
  ('file_title', 'file_title', 'category', 'com_virtuemart', 'export'),
  ('file_description', 'file_description', 'category', 'com_virtuemart', 'export'),
  ('file_meta', 'file_meta', 'category', 'com_virtuemart', 'export'),
  ('file_ordering', 'file_ordering', 'category', 'com_virtuemart', 'export'),
  ('file_lang', 'file_lang', 'category', 'com_virtuemart', 'export'),

  /* VirtueMart calculation rule export */
  ('currency_code_3', 'currency_code_3', 'calc', 'com_virtuemart', 'export'),
  ('category_path', 'category_path', 'calc', 'com_virtuemart', 'export'),
  ('shopper_group_name', 'shopper_group_name', 'calc', 'com_virtuemart', 'export'),
  ('country_name', 'country_name', 'calc', 'com_virtuemart', 'export'),
  ('country_2_code', 'country_2_code', 'calc', 'com_virtuemart', 'export'),
  ('country_3_code', 'country_3_code', 'calc', 'com_virtuemart', 'export'),
  ('state_name', 'state_name', 'calc', 'com_virtuemart', 'export'),
  ('state_2_code', 'state_2_code', 'calc', 'com_virtuemart', 'export'),
  ('state_3_code', 'state_3_code', 'calc', 'com_virtuemart', 'export'),

  /* VirtueMart Manufacturer export */
  ('mf_name', 'mf_name', 'manufacturer', 'com_virtuemart', 'export'),
  ('mf_name_trans', 'mf_name_trans', 'manufacturer', 'com_virtuemart', 'export'),
  ('mf_email', 'mf_email', 'manufacturer', 'com_virtuemart', 'export'),
  ('mf_desc', 'mf_desc', 'manufacturer', 'com_virtuemart', 'export'),
  ('mf_url', 'mf_url', 'manufacturer', 'com_virtuemart', 'export'),
  ('slug', 'slug', 'manufacturer', 'com_virtuemart', 'export'),
  ('mf_category_name', 'mf_category_name', 'manufacturer', 'com_virtuemart', 'export'),
  ('file_url', 'file_url', 'manufacturer', 'com_virtuemart', 'export'),
  ('file_url_thumb', 'file_url_thumb', 'manufacturer', 'com_virtuemart', 'export'),
  ('file_title', 'file_title', 'manufacturer', 'com_virtuemart', 'export'),
  ('file_description', 'file_description', 'manufacturer', 'com_virtuemart', 'export'),
  ('file_meta', 'file_meta', 'manufacturer', 'com_virtuemart', 'export'),
  ('file_ordering', 'file_ordering', 'manufacturer', 'com_virtuemart', 'export'),
  ('file_lang', 'file_lang', 'manufacturer', 'com_virtuemart', 'export'),

  /* VirtueMart Medias export */
  ('custom', 'custom', 'media', 'com_virtuemart', 'export'),
  ('product_sku', 'product_sku', 'media', 'com_virtuemart', 'export'),

  /* Price import */
  ('skip', 'skip', 'price', 'com_virtuemart', 'import'),
  ('combine', 'combine', 'price', 'com_virtuemart', 'import'),
  ('price_delete', 'price_delete', 'price', 'com_virtuemart', 'import'),
  ('product_name', 'product_name', 'priceexport', 'com_virtuemart', 'import'),
  ('product_sku', 'product_sku', 'price', 'com_virtuemart', 'import'),
  ('shopper_group_name', 'shopper_group_name', 'price', 'com_virtuemart', 'import'),
  ('shopper_group_name_new', 'shopper_group_name_new', 'price', 'com_virtuemart', 'import'),
  ('product_price_new', 'product_price_new', 'price', 'com_virtuemart', 'import'),

  /* Price export */
  ('custom', 'custom', 'price', 'com_virtuemart', 'export'),
  ('product_sku', 'product_sku', 'price', 'com_virtuemart', 'export'),
  ('shopper_group_name', 'shopper_group_name', 'price', 'com_virtuemart', 'export'),

  /* VirtueMart order export */
  ('custom', 'custom', 'order', 'com_virtuemart', 'export'),
  ('user_currency', 'user_currency', 'order', 'com_virtuemart', 'export'), /* In the format EUR */
  ('payment_element', 'payment_element', 'order', 'com_virtuemart', 'export'),
  ('state_name', 'state_name', 'order', 'com_virtuemart', 'export'),
  ('state_2_code', 'state_2_code', 'order', 'com_virtuemart', 'export'),
  ('state_3_code', 'state_3_code', 'order', 'com_virtuemart', 'export'),
  ('virtuemart_state_id', 'virtuemart_state_id', 'order', 'com_virtuemart', 'export'),
  ('country_name', 'country_name', 'order', 'com_virtuemart', 'export'),
  ('country_2_code', 'country_2_code', 'order', 'com_virtuemart', 'export'),
  ('country_3_code', 'country_3_code', 'order', 'com_virtuemart', 'export'),
  ('virtuemart_country_id', 'virtuemart_country_id', 'order', 'com_virtuemart', 'export'),
  ('shipment_element', 'shipment_element', 'order', 'com_virtuemart', 'export'),
  ('shipment_name', 'shipment_name', 'order', 'com_virtuemart', 'export'),
  ('order_status_name', 'order_status_name', 'order', 'com_virtuemart', 'export'),
  ('full_name', 'full_name', 'order', 'com_virtuemart', 'export'),
  ('shipping_full_name', 'shipping_full_name', 'order', 'com_virtuemart', 'export'),
  ('username', 'username', 'order', 'com_virtuemart', 'export'),
  ('total_order_items', 'total_order_items', 'order', 'com_virtuemart', 'export'),
  ('discount_percentage', 'discount_percentage', 'order', 'com_virtuemart', 'export'),
  ('product_price_total', 'product_price_total', 'order', 'com_virtuemart', 'export'),
  ('invoice_number', 'invoice_number', 'order', 'com_virtuemart', 'export'),
  ('payment_name', 'payment_name', 'order', 'com_virtuemart', 'export'),
  ('order_weight', 'order_weight', 'order', 'com_virtuemart', 'export'),

  /* VirtueMart order advanced export */
  ('custom', 'custom', 'orderadvanced', 'com_virtuemart', 'export'),
  ('user_currency', 'user_currency', 'orderadvanced', 'com_virtuemart', 'export'), /* In the format EUR */
  ('payment_element', 'payment_element', 'orderadvanced', 'com_virtuemart', 'export'),
  ('state_name', 'state_name', 'orderadvanced', 'com_virtuemart', 'export'),
  ('state_2_code', 'state_2_code', 'orderadvanced', 'com_virtuemart', 'export'),
  ('state_3_code', 'state_3_code', 'orderadvanced', 'com_virtuemart', 'export'),
  ('virtuemart_state_id', 'virtuemart_state_id', 'orderadvanced', 'com_virtuemart', 'export'),
  ('country_name', 'country_name', 'orderadvanced', 'com_virtuemart', 'export'),
  ('country_2_code', 'country_2_code', 'orderadvanced', 'com_virtuemart', 'export'),
  ('country_3_code', 'country_3_code', 'orderadvanced', 'com_virtuemart', 'export'),
  ('virtuemart_country_id', 'virtuemart_country_id', 'orderadvanced', 'com_virtuemart', 'export'),
  ('shipment_element', 'shipment_element', 'orderadvanced', 'com_virtuemart', 'export'),
  ('order_status_name', 'order_status_name', 'orderadvanced', 'com_virtuemart', 'export'),
  ('full_name', 'full_name', 'orderadvanced', 'com_virtuemart', 'export'),
  ('username', 'username', 'orderadvanced', 'com_virtuemart', 'export'),
  ('total_order_items', 'total_order_items', 'orderadvanced', 'com_virtuemart', 'export'),
  ('discount_percentage', 'discount_percentage', 'orderadvanced', 'com_virtuemart', 'export'),
  ('product_price_total', 'product_price_total', 'orderadvanced', 'com_virtuemart', 'export'),
  ('invoice_number', 'invoice_number', 'orderadvanced', 'com_virtuemart', 'export'),
  ('shipment_name', 'shipment_name', 'orderadvanced', 'com_virtuemart', 'export'),
  ('payment_name', 'payment_name', 'orderadvanced', 'com_virtuemart', 'export'),
  ('shipping_company', 'shipping_company', 'orderadvanced', 'com_virtuemart', 'export'),
  ('shipping_title', 'shipping_title', 'orderadvanced', 'com_virtuemart', 'export'),
  ('shipping_last_name', 'shipping_last_name', 'orderadvanced', 'com_virtuemart', 'export'),
  ('shipping_first_name', 'shipping_first_name', 'orderadvanced', 'com_virtuemart', 'export'),
  ('shipping_middle_name', 'shipping_middle_name', 'orderadvanced', 'com_virtuemart', 'export'),
  ('shipping_full_name', 'shipping_full_name', 'orderadvanced', 'com_virtuemart', 'export'),
  ('shipping_phone_1', 'shipping_phone_1', 'orderadvanced', 'com_virtuemart', 'export'),
  ('shipping_phone_2', 'shipping_phone_2', 'orderadvanced', 'com_virtuemart', 'export'),
  ('shipping_fax', 'shipping_fax', 'orderadvanced', 'com_virtuemart', 'export'),
  ('shipping_address_1', 'shipping_address_1', 'orderadvanced', 'com_virtuemart', 'export'),
  ('shipping_address_2', 'shipping_address_2', 'orderadvanced', 'com_virtuemart', 'export'),
  ('shipping_city', 'shipping_city', 'orderadvanced', 'com_virtuemart', 'export'),
  ('shipping_state_name', 'shipping_state_name', 'orderadvanced', 'com_virtuemart', 'export'),
  ('shipping_state_2_code', 'shipping_state_2_code', 'orderadvanced', 'com_virtuemart', 'export'),
  ('shipping_state_3_code', 'shipping_state_3_code', 'orderadvanced', 'com_virtuemart', 'export'),
  ('shipping_country_name', 'shipping_country_name', 'orderadvanced', 'com_virtuemart', 'export'),
  ('shipping_country_2_code', 'shipping_country_2_code', 'orderadvanced', 'com_virtuemart', 'export'),
  ('shipping_country_3_code', 'shipping_country_3_code', 'orderadvanced', 'com_virtuemart', 'export'),
  ('shipping_zip', 'shipping_zip', 'orderadvanced', 'com_virtuemart', 'export'),
  ('shipping_email', 'shipping_email', 'orderadvanced', 'com_virtuemart', 'export'),

  /* VirtueMart order item export */
  ('full_name', 'fullname', 'orderitem', 'com_virtuemart', 'export'),
  ('product_sku', 'product_sku', 'orderitem', 'com_virtuemart', 'export'),
  ('order_status_name', 'order_status_name', 'orderitem', 'com_virtuemart', 'export'),

  /* VirtueMart Product export */
  ('custom', 'custom', 'product', 'com_virtuemart', 'export'),
  ('product_price', 'product_price', 'product', 'com_virtuemart', 'export'),
  ('shopper_group_name', 'shopper_group_name', 'product', 'com_virtuemart', 'export'),
  ('shopper_group_name_price', 'shopper_group_name_price', 'product', 'com_virtuemart', 'export'),
  ('related_products', 'related_products', 'product', 'com_virtuemart', 'export'),
  ('related_categories', 'related_categories', 'product', 'com_virtuemart', 'export'),
  ('category_id', 'category_id', 'product', 'com_virtuemart', 'export'),
  ('category_path', 'category_path', 'product', 'com_virtuemart', 'export'),
  ('category_name', 'category_name', 'product', 'com_virtuemart', 'export'),
  ('product_box', 'product_box', 'product', 'com_virtuemart', 'export'),
  ('product_parent_sku', 'product_parent_sku', 'product', 'com_virtuemart', 'export'),
  ('product_name', 'product_name', 'product', 'com_virtuemart', 'export'),
  ('product_s_desc', 'product_s_desc', 'product', 'com_virtuemart', 'export'),
  ('product_desc', 'product_desc', 'product', 'com_virtuemart', 'export'),
  ('metadesc', 'metadesc', 'product', 'com_virtuemart', 'export'),
  ('metakey', 'metakey', 'product', 'com_virtuemart', 'export'),
  ('customtitle', 'customtitle', 'product', 'com_virtuemart', 'export'),
  ('slug', 'slug', 'product', 'com_virtuemart', 'export'),
  ('picture_url', 'picture_url', 'product', 'com_virtuemart', 'export'),
  ('picture_url_thumb', 'picture_url_thumb', 'product', 'com_virtuemart', 'export'),
  ('override', 'override', 'product', 'com_virtuemart', 'export'),
  ('product_override_price', 'product_override_price', 'product', 'com_virtuemart', 'export'),
  ('product_currency', 'product_currency', 'product', 'com_virtuemart', 'export'),
  ('basepricewithtax', 'basepricewithtax', 'product', 'com_virtuemart', 'export'),
  ('discountedpricewithouttax', 'discountedpricewithouttax', 'product', 'com_virtuemart', 'export'),
  ('pricebeforetax', 'pricebeforetax', 'product', 'com_virtuemart', 'export'),
  ('salesprice', 'salesprice', 'product', 'com_virtuemart', 'export'),
  ('taxamount', 'taxamount', 'product', 'com_virtuemart', 'export'),
  ('discountamount', 'discountamount', 'product', 'com_virtuemart', 'export'),
  ('pricewithouttax', 'pricewithouttax', 'product', 'com_virtuemart', 'export'),
  ('manufacturer_name', 'manufacturer_name', 'product', 'com_virtuemart', 'export'),
  ('custom_title', 'custom_title', 'product', 'com_virtuemart', 'export'),
  ('custom_value', 'custom_value', 'product', 'com_virtuemart', 'export'),
  ('custom_price', 'custom_price', 'product', 'com_virtuemart', 'export'),
  ('custom_param', 'custom_param', 'product', 'com_virtuemart', 'export'),
  ('custom_ordering', 'custom_ordering', 'product', 'com_virtuemart', 'export'),
  ('file_url', 'file_url', 'product', 'com_virtuemart', 'export'),
  ('file_url_thumb', 'file_url_thumb', 'product', 'com_virtuemart', 'export'),
  ('file_ordering', 'file_ordering', 'product', 'com_virtuemart', 'export'),
  ('file_title', 'file_title', 'product', 'com_virtuemart', 'export'),
  ('file_description', 'file_description', 'product', 'com_virtuemart', 'export'),
  ('file_meta', 'file_meta', 'product', 'com_virtuemart', 'export'),
  ('min_order_level', 'min_order_level', 'product', 'com_virtuemart', 'export'),
  ('max_order_level', 'max_order_level', 'product', 'com_virtuemart', 'export'),
  ('step_order_level', 'step_order_level', 'product', 'com_virtuemart', 'export'),
  ('product_tax_id', 'product_tax_id', 'product', 'com_virtuemart', 'export'),
  ('product_discount_id', 'product_discount_id', 'product', 'com_virtuemart', 'export'),
  ('product_discount', 'product_discount', 'product', 'com_virtuemart', 'export'),
  ('product_ordering', 'product_ordering', 'product', 'com_virtuemart', 'export'),
  ('custom_disabler', 'custom_disabler', 'product', 'com_virtuemart', 'export'),
  ('custom_override', 'custom_override', 'product', 'com_virtuemart', 'export'),

  /* VirtueMart Google Merchant export */
  ('custom', 'custom', 'google', 'com_virtuemart', 'export'),
  ('product_price', 'product_price', 'google', 'com_virtuemart', 'export'),
  ('shopper_group_name', 'shopper_group_name', 'google', 'com_virtuemart', 'export'),
  ('shopper_group_name_price', 'shopper_group_name_price', 'google', 'com_virtuemart', 'export'),
  ('related_products', 'related_products', 'google', 'com_virtuemart', 'export'),
  ('related_categories', 'related_categories', 'google', 'com_virtuemart', 'export'),
  ('category_id', 'category_id', 'google', 'com_virtuemart', 'export'),
  ('category_path', 'category_path', 'google', 'com_virtuemart', 'export'),
  ('category_name', 'category_name', 'google', 'com_virtuemart', 'export'),
  ('product_box', 'product_box', 'google', 'com_virtuemart', 'export'),
  ('product_parent_sku', 'product_parent_sku', 'google', 'com_virtuemart', 'export'),
  ('product_name', 'product_name', 'google', 'com_virtuemart', 'export'),
  ('product_s_desc', 'product_s_desc', 'google', 'com_virtuemart', 'export'),
  ('product_desc', 'product_desc', 'google', 'com_virtuemart', 'export'),
  ('metadesc', 'metadesc', 'google', 'com_virtuemart', 'export'),
  ('metakey', 'metakey', 'google', 'com_virtuemart', 'export'),
  ('customtitle', 'customtitle', 'google', 'com_virtuemart', 'export'),
  ('slug', 'slug', 'google', 'com_virtuemart', 'export'),
  ('picture_url', 'picture_url', 'google', 'com_virtuemart', 'export'),
  ('picture_url_thumb', 'picture_url_thumb', 'google', 'com_virtuemart', 'export'),
  ('override', 'override', 'google', 'com_virtuemart', 'export'),
  ('product_override_price', 'product_override_price', 'google', 'com_virtuemart', 'export'),
  ('product_currency', 'product_currency', 'google', 'com_virtuemart', 'export'),
  ('custom_shipping', 'custom_shipping', 'google', 'com_virtuemart', 'export'),
  ('basepricewithtax', 'basepricewithtax', 'google', 'com_virtuemart', 'export'),
  ('discountedpricewithouttax', 'discountedpricewithouttax', 'google', 'com_virtuemart', 'export'),
  ('pricebeforetax', 'pricebeforetax', 'google', 'com_virtuemart', 'export'),
  ('salesprice', 'salesprice', 'google', 'com_virtuemart', 'export'),
  ('taxamount', 'taxamount', 'google', 'com_virtuemart', 'export'),
  ('discountamount', 'discountamount', 'google', 'com_virtuemart', 'export'),
  ('pricewithouttax', 'pricewithouttax', 'google', 'com_virtuemart', 'export'),
  ('manufacturer_name', 'manufacturer_name', 'google', 'com_virtuemart', 'export'),
  ('custom_title', 'custom_title', 'google', 'com_virtuemart', 'export'),
  ('custom_value', 'custom_value', 'google', 'com_virtuemart', 'export'),
  ('custom_price', 'custom_price', 'google', 'com_virtuemart', 'export'),
  ('custom_param', 'custom_param', 'google', 'com_virtuemart', 'export'),
  ('custom_ordering', 'custom_ordering', 'google', 'com_virtuemart', 'export'),
  ('file_url', 'file_url', 'google', 'com_virtuemart', 'export'),
  ('file_url_thumb', 'file_url_thumb', 'google', 'com_virtuemart', 'export'),
  ('file_ordering', 'file_ordering', 'google', 'com_virtuemart', 'export'),
  ('file_title', 'file_title', 'google', 'com_virtuemart', 'export'),
  ('file_description', 'file_description', 'google', 'com_virtuemart', 'export'),
  ('file_meta', 'file_meta', 'google', 'com_virtuemart', 'export'),
  ('min_order_level', 'min_order_level', 'google', 'com_virtuemart', 'export'),
  ('max_order_level', 'max_order_level', 'google', 'com_virtuemart', 'export'),
  ('step_order_level', 'step_order_level', 'google', 'com_virtuemart', 'export'),
  ('product_tax_id', 'product_tax_id', 'google', 'com_virtuemart', 'export'),
  ('product_discount_id', 'product_discount_id', 'google', 'com_virtuemart', 'export'),
  ('product_discount', 'product_discount', 'google', 'com_virtuemart', 'export'),
  ('product_ordering', 'product_ordering', 'google', 'com_virtuemart', 'export'),
  ('custom_disabler', 'custom_disabler', 'google', 'com_virtuemart', 'export'),
  ('custom_override', 'custom_override', 'google', 'com_virtuemart', 'export'),

  /* VirtueMart Yandex export */
  ('custom', 'custom', 'yandex', 'com_virtuemart', 'export'),
  ('product_price', 'product_price', 'yandex', 'com_virtuemart', 'export'),
  ('shopper_group_name', 'shopper_group_name', 'yandex', 'com_virtuemart', 'export'),
  ('related_products', 'related_products', 'yandex', 'com_virtuemart', 'export'),
  ('category_id', 'category_id', 'yandex', 'com_virtuemart', 'export'),
  ('category_path', 'category_path', 'yandex', 'com_virtuemart', 'export'),
  ('product_box', 'product_box', 'yandex', 'com_virtuemart', 'export'),
  ('product_parent_sku', 'product_parent_sku', 'yandex', 'com_virtuemart', 'export'),
  ('product_name', 'product_name', 'yandex', 'com_virtuemart', 'export'),
  ('product_s_desc', 'product_s_desc', 'yandex', 'com_virtuemart', 'export'),
  ('product_desc', 'product_desc', 'yandex', 'com_virtuemart', 'export'),
  ('metadesc', 'metadesc', 'yandex', 'com_virtuemart', 'export'),
  ('metakey', 'metakey', 'yandex', 'com_virtuemart', 'export'),
  ('customtitle', 'customtitle', 'yandex', 'com_virtuemart', 'export'),
  ('slug', 'slug', 'yandex', 'com_virtuemart', 'export'),
  ('picture_url', 'picture_url', 'yandex', 'com_virtuemart', 'export'),
  ('override', 'override', 'yandex', 'com_virtuemart', 'export'),
  ('product_override_price', 'product_override_price', 'yandex', 'com_virtuemart', 'export'),
  ('product_currency', 'product_currency', 'yandex', 'com_virtuemart', 'export'),
  ('custom_shipping', 'custom_shipping', 'yandex', 'com_virtuemart', 'export'),
  ('basepricewithtax', 'basepricewithtax', 'yandex', 'com_virtuemart', 'export'),
  ('discountedpricewithouttax', 'discountedpricewithouttax', 'yandex', 'com_virtuemart', 'export'),
  ('pricebeforetax', 'pricebeforetax', 'yandex', 'com_virtuemart', 'export'),
  ('salesprice', 'salesprice', 'yandex', 'com_virtuemart', 'export'),
  ('taxamount', 'taxamount', 'yandex', 'com_virtuemart', 'export'),
  ('discountamount', 'discountamount', 'yandex', 'com_virtuemart', 'export'),
  ('pricewithouttax', 'pricewithouttax', 'yandex', 'com_virtuemart', 'export'),
  ('manufacturer_name', 'manufacturer_name', 'yandex', 'com_virtuemart', 'export'),
  ('custom_title', 'custom_title', 'yandex', 'com_virtuemart', 'export'),
  ('custom_value', 'custom_value', 'yandex', 'com_virtuemart', 'export'),
  ('custom_price', 'custom_price', 'yandex', 'com_virtuemart', 'export'),
  ('custom_param', 'custom_param', 'yandex', 'com_virtuemart', 'export'),
  ('file_url', 'file_url', 'yandex', 'com_virtuemart', 'export'),
  ('file_url_thumb', 'file_url_thumb', 'yandex', 'com_virtuemart', 'export'),
  ('file_ordering', 'file_ordering', 'yandex', 'com_virtuemart', 'export'),
  ('min_order_level', 'min_order_level', 'yandex', 'com_virtuemart', 'export'),
  ('max_order_level', 'max_order_level', 'yandex', 'com_virtuemart', 'export'),
  ('product_tax_id', 'product_tax_id', 'yandex', 'com_virtuemart', 'export'),
  ('product_discount_id', 'product_discount_id', 'yandex', 'com_virtuemart', 'export'),

  /* VirtueMart Rating export */
  ('custom', 'custom', 'rating', 'com_virtuemart', 'export'),
  ('product_sku', 'product_sku', 'rating', 'com_virtuemart', 'export'),
  ('vote', 'vote', 'rating', 'com_virtuemart', 'export'),
  ('username', 'username', 'rating', 'com_virtuemart', 'export'),

  /* VirtueMart Shopperfield export */
  ('custom', 'custom', 'shopperfield', 'com_virtuemart', 'export'),

  /* VirtueMart Shipping rates import */
  ('skip', 'skip', 'shippingrate', 'com_virtuemart', 'import'),
  ('shipment_name', 'shipment_name', 'shippingrate', 'com_virtuemart', 'import'),
  ('shipment_desc', 'shipment_desc', 'shippingrate', 'com_virtuemart', 'import'),
  ('slug', 'slug', 'shippingrate', 'com_virtuemart', 'import'),
  ('shippingrate_delete', 'shippingrate_delete', 'shippingrate', 'com_virtuemart', 'import'),
  ('shipment_logos', 'shipment_logos', 'shippingrate', 'com_virtuemart', 'import'),
  ('show_on_pdetails', 'show_on_pdetails', 'shippingrate', 'com_virtuemart', 'import'),
  ('countries', 'countries', 'shippingrate', 'com_virtuemart', 'import'),
  ('zip_start', 'zip_start', 'shippingrate', 'com_virtuemart', 'import'),
  ('zip_stop', 'zip_stop', 'shippingrate', 'com_virtuemart', 'import'),
  ('weight_start', 'weight_start', 'shippingrate', 'com_virtuemart', 'import'),
  ('weight_stop', 'weight_stop', 'shippingrate', 'com_virtuemart', 'import'),
  ('weight_unit', 'weight_unit', 'shippingrate', 'com_virtuemart', 'import'),
  ('nbproducts_start', 'nbproducts_start', 'shippingrate', 'com_virtuemart', 'import'),
  ('nbproducts_stop', 'nbproducts_stop', 'shippingrate', 'com_virtuemart', 'import'),
  ('orderamount_start', 'orderamount_start', 'shippingrate', 'com_virtuemart', 'import'),
  ('orderamount_stop', 'orderamount_stop', 'shippingrate', 'com_virtuemart', 'import'),
  ('shipment_cost', 'shipment_cost', 'shippingrate', 'com_virtuemart', 'import'),
  ('package_fee', 'package_fee', 'shippingrate', 'com_virtuemart', 'import'),
  ('tax_id', 'tax_id', 'shippingrate', 'com_virtuemart', 'import'),
  ('free_shipment', 'free_shipment', 'shippingrate', 'com_virtuemart', 'import'),
  ('tax', 'tax', 'shippingrate', 'com_virtuemart', 'import'),
  ('shopper_group_name', 'shopper_group_name', 'shippingrate', 'com_virtuemart', 'import'),
  ('shipment_name_trans', 'shipment_name_trans', 'shippingrate', 'com_virtuemart', 'import'),

  /* VirtueMart Shipping rates export */
  ('custom', 'custom', 'shippingrate', 'com_virtuemart', 'export'),
  ('shipment_name', 'shipment_name', 'shippingrate', 'com_virtuemart', 'export'),
  ('shipment_desc', 'shipment_desc', 'shippingrate', 'com_virtuemart', 'export'),
  ('slug', 'slug', 'shippingrate', 'com_virtuemart', 'export'),
  ('shipment_logos', 'shipment_logos', 'shippingrate', 'com_virtuemart', 'export'),
  ('countries', 'countries', 'shippingrate', 'com_virtuemart', 'export'),
  ('zip_start', 'zip_start', 'shippingrate', 'com_virtuemart', 'export'),
  ('zip_stop', 'zip_stop', 'shippingrate', 'com_virtuemart', 'export'),
  ('weight_start', 'weight_start', 'shippingrate', 'com_virtuemart', 'export'),
  ('weight_stop', 'weight_stop', 'shippingrate', 'com_virtuemart', 'export'),
  ('weight_unit', 'weight_unit', 'shippingrate', 'com_virtuemart', 'export'),
  ('nbproducts_start', 'nbproducts_start', 'shippingrate', 'com_virtuemart', 'export'),
  ('nbproducts_stop', 'nbproducts_stop', 'shippingrate', 'com_virtuemart', 'export'),
  ('orderamount_start', 'orderamount_start', 'shippingrate', 'com_virtuemart', 'export'),
  ('orderamount_stop', 'orderamount_stop', 'shippingrate', 'com_virtuemart', 'export'),
  ('cost', 'cost', 'shippingrate', 'com_virtuemart', 'export'),
  ('package_fee', 'package_fee', 'shippingrate', 'com_virtuemart', 'export'),
  ('tax_id', 'tax_id', 'shippingrate', 'com_virtuemart', 'export'),
  ('free_shipment', 'free_shipment', 'shippingrate', 'com_virtuemart', 'export'),
  ('tax', 'tax', 'shippingrate', 'com_virtuemart', 'export'),
  ('shopper_group_name', 'shopper_group_name', 'shippingrate', 'com_virtuemart', 'export'),

  /* VirtueMart Userinfo export */
  ('custom', 'custom', 'userinfo', 'com_virtuemart', 'export'),
  ('full_name', 'fullname', 'userinfo', 'com_virtuemart', 'export'),
  ('vendor_name', 'vendor_name', 'userinfo', 'com_virtuemart', 'export'),
  ('shopper_group_name', 'shopper_group_name', 'userinfo', 'com_virtuemart', 'export'),
  ('address_type', 'address_type', 'userinfo', 'com_virtuemart', 'export'),
  ('address_type_name', 'address_type_name', 'userinfo', 'com_virtuemart', 'export'),
  ('usergroup_name', 'usergroup_name', 'userinfo', 'com_virtuemart', 'export'),
  ('country_name', 'country_name', 'userinfo', 'com_virtuemart', 'export'),
  ('country_2_code', 'country_2_code', 'userinfo', 'com_virtuemart', 'export'),
  ('country_3_code', 'country_3_code', 'userinfo', 'com_virtuemart', 'export'),
  ('state_name', 'state_name', 'userinfo', 'com_virtuemart', 'export'),
  ('state_2_code', 'state_2_code', 'userinfo', 'com_virtuemart', 'export'),
  ('state_3_code', 'state_3_code', 'userinfo', 'com_virtuemart', 'export'),

  /* VirtueMart Waiting users export */
  ('custom', 'custom', 'waitinglist', 'com_virtuemart', 'export'),
  ('product_sku', 'product_sku', 'waitinglist', 'com_virtuemart', 'export'),
  ('username', 'username', 'waitinglist', 'com_virtuemart', 'export'),

  /* VirtueMart Custom field export */
  ('custom', 'custom', 'customfield', 'com_virtuemart', 'export'),
  ('plugin_name', 'plugin_name', 'customfield', 'com_virtuemart', 'export'),
  ('vendor_name', 'vendor_name', 'customfield', 'com_virtuemart', 'export'),

  /* VirtueMart SnelStart export */
  ('custom', 'custom', 'snelstart', 'com_virtuemart', 'export'),
  ('user_currency', 'user_currency', 'snelstart', 'com_virtuemart', 'export'), /* In the format EUR */
  ('payment_element', 'payment_element', 'snelstart', 'com_virtuemart', 'export'),
  ('state_name', 'state_name', 'snelstart', 'com_virtuemart', 'export'),
  ('state_2_code', 'state_2_code', 'snelstart', 'com_virtuemart', 'export'),
  ('state_3_code', 'state_3_code', 'snelstart', 'com_virtuemart', 'export'),
  ('virtuemart_state_id', 'virtuemart_state_id', 'snelstart', 'com_virtuemart', 'export'),
  ('country_name', 'country_name', 'snelstart', 'com_virtuemart', 'export'),
  ('country_2_code', 'country_2_code', 'snelstart', 'com_virtuemart', 'export'),
  ('country_3_code', 'country_3_code', 'snelstart', 'com_virtuemart', 'export'),
  ('virtuemart_country_id', 'virtuemart_country_id', 'snelstart', 'com_virtuemart', 'export'),
  ('shipment_element', 'shipment_element', 'snelstart', 'com_virtuemart', 'export'),
  ('order_status_name', 'order_status_name', 'snelstart', 'com_virtuemart', 'export'),
  ('full_name', 'full_name', 'snelstart', 'com_virtuemart', 'export'),
  ('username', 'username', 'snelstart', 'com_virtuemart', 'export'),
  ('total_order_items', 'total_order_items', 'snelstart', 'com_virtuemart', 'export'),
  ('discount_percentage', 'discount_percentage', 'snelstart', 'com_virtuemart', 'export'),
  ('product_price_total', 'product_price_total', 'snelstart', 'com_virtuemart', 'export'),
  ('invoice_number', 'invoice_number', 'snelstart', 'com_virtuemart', 'export'),
  ('shipment_name', 'shipment_name', 'snelstart', 'com_virtuemart', 'export'),
  ('payment_name', 'payment_name', 'snelstart', 'com_virtuemart', 'export'),
  ('shipping_company', 'shipping_company', 'snelstart', 'com_virtuemart', 'export'),
  ('shipping_title', 'shipping_title', 'snelstart', 'com_virtuemart', 'export'),
  ('shipping_last_name', 'shipping_last_name', 'snelstart', 'com_virtuemart', 'export'),
  ('shipping_first_name', 'shipping_first_name', 'snelstart', 'com_virtuemart', 'export'),
  ('shipping_middle_name', 'shipping_middle_name', 'snelstart', 'com_virtuemart', 'export'),
  ('shipping_full_name', 'shipping_full_name', 'snelstart', 'com_virtuemart', 'export'),
  ('shipping_phone_1', 'shipping_phone_1', 'snelstart', 'com_virtuemart', 'export'),
  ('shipping_phone_2', 'shipping_phone_2', 'snelstart', 'com_virtuemart', 'export'),
  ('shipping_fax', 'shipping_fax', 'snelstart', 'com_virtuemart', 'export'),
  ('shipping_address_1', 'shipping_address_1', 'snelstart', 'com_virtuemart', 'export'),
  ('shipping_address_2', 'shipping_address_2', 'snelstart', 'com_virtuemart', 'export'),
  ('shipping_city', 'shipping_city', 'snelstart', 'com_virtuemart', 'export'),
  ('shipping_state_name', 'shipping_state_name', 'snelstart', 'com_virtuemart', 'export'),
  ('shipping_state_2_code', 'shipping_state_2_code', 'snelstart', 'com_virtuemart', 'export'),
  ('shipping_state_3_code', 'shipping_state_3_code', 'snelstart', 'com_virtuemart', 'export'),
  ('shipping_country_name', 'shipping_country_name', 'snelstart', 'com_virtuemart', 'export'),
  ('shipping_country_2_code', 'shipping_country_2_code', 'snelstart', 'com_virtuemart', 'export'),
  ('shipping_country_3_code', 'shipping_country_3_code', 'snelstart', 'com_virtuemart', 'export'),
  ('shipping_zip', 'shipping_zip', 'snelstart', 'com_virtuemart', 'export'),
  ('shipping_email', 'shipping_email', 'snelstart', 'com_virtuemart', 'export'),
  ('product_subtotal_discount_percentage', 'product_subtotal_discount_percentage', 'snelstart', 'com_virtuemart', 'export'),

  /* VirtueMart Related products import */
  ('skip', 'skip', 'relatedproduct', 'com_virtuemart', 'import'),
  ('combine', 'combine', 'relatedproduct', 'com_virtuemart', 'import'),
  ('vendor_id', 'vendor_id', 'relatedproduct', 'com_virtuemart', 'import'),
  ('product_sku', 'product_sku', 'relatedproduct', 'com_virtuemart', 'import'),
  ('related_products', 'related_products', 'relatedproduct', 'com_virtuemart', 'import'),

  /* VirtueMart Media products import */
  ('skip', 'skip', 'mediaproduct', 'com_virtuemart', 'import'),
  ('combine', 'combine', 'mediaproduct', 'com_virtuemart', 'import'),
  ('product_sku', 'product_sku', 'mediaproduct', 'com_virtuemart', 'import'),
  ('file_url', 'file_url', 'mediaproduct', 'com_virtuemart', 'import'),
  ('file_url_thumb', 'file_url_thumb', 'mediaproduct', 'com_virtuemart', 'import'),
  ('file_title', 'file_title', 'mediaproduct', 'com_virtuemart', 'import'),
  ('file_description', 'file_description', 'mediaproduct', 'com_virtuemart', 'import'),
  ('file_meta', 'file_meta', 'mediaproduct', 'com_virtuemart', 'import'),
  ('file_ordering', 'file_ordering', 'mediaproduct', 'com_virtuemart', 'import'),

  /* VirtueMart Manufacturer category export */
  ('custom', 'custom', 'manufacturercategory', 'com_virtuemart', 'export'),
  ('mf_category_name', 'mf_categoryname', 'manufacturercategory', 'com_virtuemart', 'export'),
  ('mf_category_name_trans', 'mf_category_name_trans', 'manufacturercategory', 'com_virtuemart', 'export'),
  ('mf_category_desc', 'mf_category_desc', 'manufacturercategory', 'com_virtuemart', 'export'),
  ('slug', 'slug', 'manufacturercategory', 'com_virtuemart', 'export'),

  /* VirtueMart Availability products import */
  ('skip', 'skip', 'availabilityproduct', 'com_virtuemart', 'import'),
  ('combine', 'combine', 'availabilityproduct', 'com_virtuemart', 'import'),
  ('product_sku', 'product_sku', 'availabilityproduct', 'com_virtuemart', 'import'),
  ('product_in_stock', 'file_url', 'availabilityproduct', 'com_virtuemart', 'import'),
  ('product_available_date', 'product_available_date', 'availabilityproduct', 'com_virtuemart', 'import');

/* Custom fields */
INSERT IGNORE INTO `#__csvi_availablefields` (csvi_name, component_name, component_table, component, action)
  (SELECT
     TRIM(custom_title),
     TRIM(custom_title),
     'product',
     'com_virtuemart',
     'import'
   FROM `#__virtuemart_customs`
   WHERE field_type IN ('S', 'I', 'B', 'D', 'T', 'M', 'Y', 'X')
  );

INSERT IGNORE INTO `#__csvi_availablefields` (csvi_name, component_name, component_table, component, action)
  (SELECT
     TRIM(custom_title),
     TRIM(custom_title),
     'product',
     'com_virtuemart',
     'export'
   FROM `#__virtuemart_customs`
   WHERE field_type IN ('S', 'I', 'B', 'D', 'T', 'M', 'Y', 'X')
  );

  INSERT IGNORE INTO `#__csvi_availablefields` (csvi_name, component_name, component_table, component, action)
  (SELECT
     TRIM(custom_title),
     TRIM(custom_title),
     'google',
     'com_virtuemart',
     'export'
   FROM `#__virtuemart_customs`
   WHERE field_type IN ('S', 'I', 'B', 'D', 'T', 'M', 'Y', 'X')
  );
