/* Joomla content import */
INSERT IGNORE INTO `#__csvi_availablefields` (`csvi_name`, `component_name`, `component_table`, `component`, `action`) VALUES
('skip', 'skip', 'content', 'com_content', 'import'),
('combine', 'combine', 'content', 'com_content', 'import'),
('category_path', 'category_path', 'content', 'com_content', 'import'),
('show_title', 'show_title', 'content', 'com_content', 'import'),
('link_titles', 'link_titles', 'content', 'com_content', 'import'),
('show_intro','show_intro', 'content', 'com_content', 'import'),
('show_category', 'show_category', 'content', 'com_content', 'import'),
('link_category', 'link_category', 'content', 'com_content', 'import'),
('show_parent_category','show_parent_category', 'content', 'com_content', 'import'),
('link_parent_category','link_parent_category', 'content', 'com_content', 'import'),
('show_author', 'show_author', 'content', 'com_content', 'import'),
('link_author', 'link_author', 'content', 'com_content', 'import'),
('show_create_date','show_create_date', 'content', 'com_content', 'import'),
('show_modify_date','show_modify_date', 'content', 'com_content', 'import'),
('show_publish_date', 'show_publish_date', 'content', 'com_content', 'import'),
('show_item_navigation','show_item_navigation', 'content', 'com_content', 'import'),
('show_icons','show_icons', 'content', 'com_content', 'import'),
('show_print_icon', 'show_print_icon', 'content', 'com_content', 'import'),
('show_email_icon', 'show_email_icon', 'content', 'com_content', 'import'),
('show_vote', 'show_vote', 'content', 'com_content', 'import'),
('show_hits', 'show_hits', 'content', 'com_content', 'import'),
('show_noauth', 'show_noauth', 'content', 'com_content', 'import'),
('urls_position', 'urls_position', 'content', 'com_content', 'import'),
('alternative_readmore','alternative_readmore', 'content', 'com_content', 'import'),
('article_layout','article_layout', 'content', 'com_content', 'import'),
('show_publishing_options', 'show_publishing_options', 'content', 'com_content', 'import'),
('show_article_options', 'show_article_options', 'content', 'com_content', 'import'),
('show_urls_images_backend', 'show_urls_images_backend', 'content', 'com_content', 'import'),
('show_urls_images_frontend', 'show_urls_images_frontend', 'content', 'com_content', 'import'),
('image_intro','image_intro', 'content', 'com_content', 'import'),
('float_intro','float_intro', 'content', 'com_content', 'import'),
('image_intro_alt','image_intro_alt', 'content', 'com_content', 'import'),
('image_intro_caption','image_intro_caption', 'content', 'com_content', 'import'),
('image_fulltext', 'image_fulltext', 'content', 'com_content', 'import'),
('float_fulltext', 'float_fulltext', 'content', 'com_content', 'import'),
('image_fulltext_alt', 'image_fulltext_alt', 'content', 'com_content', 'import'),
('image_fulltext_caption','image_fulltext_caption', 'content', 'com_content', 'import'),
('urla','urla', 'content', 'com_content', 'import'),
('urlatext','urlatext', 'content', 'com_content', 'import'),
('targeta', 'targeta', 'content', 'com_content', 'import'),
('urlb','urlb', 'content', 'com_content', 'import'),
('urlbtext','urlbtext', 'content', 'com_content', 'import'),
('targetb', 'targetb', 'content', 'com_content', 'import'),
('urlc','urlc', 'content', 'com_content', 'import'),
('urlctext','urlctext', 'content', 'com_content', 'import'),
('targetc', 'targetc', 'content', 'com_content', 'import'),

/* Joomla content export */
('custom', 'custom', 'content', 'com_content', 'export'),
('category_path', 'category_path', 'content', 'com_content', 'export'),
('article_url', 'article_url', 'content', 'com_content', 'export'),
('show_title', 'show_title', 'content', 'com_content', 'export'),
('link_titles', 'link_titles', 'content', 'com_content', 'export'),
('show_intro','show_intro', 'content', 'com_content', 'export'),
('show_category', 'show_category', 'content', 'com_content', 'export'),
('link_category', 'link_category', 'content', 'com_content', 'export'),
('show_parent_category','show_parent_category', 'content', 'com_content', 'export'),
('link_parent_category','link_parent_category', 'content', 'com_content', 'export'),
('show_author', 'show_author', 'content', 'com_content', 'export'),
('link_author', 'link_author', 'content', 'com_content', 'export'),
('show_create_date','show_create_date', 'content', 'com_content', 'export'),
('show_modify_date','show_modify_date', 'content', 'com_content', 'export'),
('show_publish_date', 'show_publish_date', 'content', 'com_content', 'export'),
('show_item_navigation','show_item_navigation', 'content', 'com_content', 'export'),
('show_icons','show_icons', 'content', 'com_content', 'export'),
('show_print_icon', 'show_print_icon', 'content', 'com_content', 'export'),
('show_email_icon', 'show_email_icon', 'content', 'com_content', 'export'),
('show_vote', 'show_vote', 'content', 'com_content', 'export'),
('show_hits', 'show_hits', 'content', 'com_content', 'export'),
('show_noauth', 'show_noauth', 'content', 'com_content', 'export'),
('urls_position', 'urls_position', 'content', 'com_content', 'export'),
('alternative_readmore','alternative_readmore', 'content', 'com_content', 'export'),
('article_layout','article_layout', 'content', 'com_content', 'export'),
('show_publishing_options', 'show_publishing_options', 'content', 'com_content', 'export'),
('show_article_options', 'show_article_options', 'content', 'com_content', 'export'),
('show_urls_images_backend', 'show_urls_images_backend', 'content', 'com_content', 'export'),
('show_urls_images_frontend', 'show_urls_images_frontend', 'content', 'com_content', 'export'),
('image_intro','image_intro', 'content', 'com_content', 'export'),
('float_intro','float_intro', 'content', 'com_content', 'export'),
('image_intro_alt','image_intro_alt', 'content', 'com_content', 'export'),
('image_intro_caption','image_intro_caption', 'content', 'com_content', 'export'),
('image_fulltext', 'image_fulltext', 'content', 'com_content', 'export'),
('float_fulltext', 'float_fulltext', 'content', 'com_content', 'export'),
('image_fulltext_alt', 'image_fulltext_alt', 'content', 'com_content', 'export'),
('image_fulltext_caption','image_fulltext_caption', 'content', 'com_content', 'export'),
('urla','urla', 'content', 'com_content', 'export'),
('urlatext','urlatext', 'content', 'com_content', 'export'),
('targeta', 'targeta', 'content', 'com_content', 'export'),
('urlb','urlb', 'content', 'com_content', 'export'),
('urlbtext','urlbtext', 'content', 'com_content', 'export'),
('targetb', 'targetb', 'content', 'com_content', 'export'),
('urlc','urlc', 'content', 'com_content', 'export'),
('urlctext','urlctext', 'content', 'com_content', 'export'),
('targetc', 'targetc', 'content', 'com_content', 'export');
